### ISSUE TITLE
WP > WebExt Identifizierung in Einstellungen funktioniert nicht

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin-productwidgets#12]
im aktuellen WP Plugin (1.0) kann man trotz aktualiserter WebExtension (3.3.1.0) in FF aktuell den „Widget bearbeiten“ Bereich nicht sehen. siehe Screenshot
![2018-02-20 09_14_11-affilinet widgets settings bluetooth kopfhorer wordpress](https://user-images.githubusercontent.com/3481571/36413495-ef79b482-161e-11e8-899f-0a9ad3c3277e.png)

**Comment by sgotre** [comment]
Beinhaltet die URL wp-admin? 
Nur dann wird das skript von der extension auch ausgeführt.

**Comment by avaffilinet** [comment]
.../wp-admin/options-general.php?page=affilinet-product-widgets-settings

Mit wp-admin in der URL funktioniert es in der Tat. Konnte den Fall ohne Anzeige nicht mehr reproduzieren.
