### ISSUE TITLE
In Browser WebExtension öffnen Button in Design>Widgets ohne Funktion

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin-productwidgets#13]
![2018-02-20 12_17_44-widgets bluetooth kopfhorer wordpress](https://user-images.githubusercontent.com/3481571/36421310-4acc0bdc-1638-11e8-829b-9d157a80570e.png)
Der Button im WP Widget, über den man das Widget in der WebExtension aufrufen und bearbeiten kann, zeigt bei Klick keine Reaktion.

**Comment by sgotre** [comment]
fixed mit nächster version. Habe die Kommunikation zwischen extension und plugin nochmal umgestellt.

**Comment by avaffilinet** [comment]
Mit der neuen Version funktioniert der Link auf die Widget Generator Seite, allerdings wird nicht das richtige Widget aufgerufen. Geht das nicht?

**Comment by sgotre** [comment]
jetzt passt es.
