### ISSUE TITLE
WP Widget Dropdown nach Klick auf speichern leer

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin-productwidgets#14]
![2018-02-20 12_20_10-widgets bluetooth kopfhorer wordpress](https://user-images.githubusercontent.com/3481571/36421397-90c3c832-1638-11e8-842e-31730c901034.png)

Speichert man die Selektion eines Product Widgets im WP Widget für die Sidebar, so ist anschließend das Dropdown für die Widget Selektion leer und man kann nichts mehr auswählen.

**Comment by sgotre** [comment]
Konnte ich nicht wirklich reproduzieren. Kann aber evtl mit #13 zusammenhängen. bitte nach nächstem update nochmal testen.

**Comment by avaffilinet** [comment]
Problem tritt mit neuer Version nicht mehr auf. Ticket zu.
