### ISSUE TITLE
Anzahl Produkte Text klebt an Zahl in Dropdown Anzeige

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin-productwidgets#15]
![2018-02-20 12_26_04-widgets namibia reiseberichte wordpress](https://user-images.githubusercontent.com/3481571/36421603-629b5f6e-1639-11e8-92c2-f9a0058392db.png)

"Produkte" darf nicht an Anzahl Produkte kleben.

**Comment by sgotre** [comment]
fixed mit nächster version
