### ISSUE TITLE
1 Produkt breites Widget nicht klickbar

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/wordpress-plugin-productwidgets#16]
Siehe Sidebar Widget: https://www.namibia-reiseberichte.de/wp-admin/customize.php?autofocus%5Bpanel%5D=widgets&return=%2Fwp-admin%2Fwidgets.php

Aufgrund 1 Produkt Breite nicht klickbar

**Comment by sgotre** [comment]
Kann ich leider nicht nachvollziehen. Habe ein Widget mit einem Produkt und kann klicken und alles funktioniert. 
Hinweis: Dein Link geht nur wenn man eingeloggt ist

**Comment by avaffilinet** [comment]
Scheint an der Design Customize Vorschau in WordPress zu liegen. Im Frontend geht es bei mir jetzt auch. Ticket schließe ich.
