### ISSUE TITLE
Create Readme File

### ISSUE THREAD

**Issue by sgotre** [affilinet/wordpress-plugin-productwidgets#17]
Please edit this file

https://github.com/affilinet/wordpress-plugin-productwidgets/blob/master/trunk/README.md

according to
https://github.com/affilinet/wordpress-plugin/blob/master/readme.txt

The content is displayed here
https://wordpress.org/plugins/affilinet-product-widgets/

WP provides a readme validator
https://wordpress.org/plugins/developers/readme-validator/

**Comment by avaffilinet** [comment]
Done

**Comment by rechl** [comment]
Updated in repo. will recheck if changes are ok

**Comment by avaffilinet** [comment]
ok
