### ISSUE TITLE
Error when saving credentials

### ISSUE THREAD

**Issue by tamend** [affilinet/wordpress-plugin-productwidgets#18]
Hi Stefan,
when I click on the button to save the credetials (see first Screen) I get an error (see Screen 2). Despite the error the Login data seem to have been saved and work fine.
Best regards
Till
![2018-02-28 10_06_01-affilinet widgets settings silent sounds wordpress](https://user-images.githubusercontent.com/4234073/36811939-7138e9b2-1cc7-11e8-900e-c74264773229.png)
![2018-02-28 10_04_21-silentsound eu_wp-admin_options php](https://user-images.githubusercontent.com/4234073/36811940-7176c714-1cc7-11e8-998f-30f5055a8ac4.png)

**Comment by sgotre** [comment]
which WP Version is that? Seems to be a compatibilty problem since error is not happening in our Plugins' files.

**Comment by tamend** [comment]
The Version is 4.5.13

**Comment by rechl** [comment]
Could not reproduce it. Is this happening always?
